### ISSUE TITLE
Feature request: hoistM and toList/fromList

### ISSUE THREAD

**Issue by NCrashed** [kowainik/typerep-map#43]
Hi, I would like to have additional helpers for the library:

``` haskell
-- Usecase: operations with map in custom monads
hoistM :: Applicative t => (forall x. f x -> t (g x)) -> TypeRepMap f -> t (TypeRepMap g) 

-- I don't sure that code below is the best design, but it should represent the main idea 
-- Usecase: serelisation/deserialisation for aeson 
newtype Wrapper f = Wrapper { unWrapper :: forall x . f x }
toList :: TypeRepMap f -> [Wrapper f]
fromList :: [Wrapper f] -> TypeRepMap f
```

**Comment by int-index** [comment]
We already have `fromList`: https://hackage.haskell.org/package/typerep-map-0.1.0/docs/Data-TypeRepMap-Internal.html#v:fromList

I guess we only need a better name for `TF`.

And instead of exporting `toList` and `fromList` as separate combinators, we could define an https://hackage.haskell.org/package/base-4.11.1.0/docs/GHC-Exts.html#t:IsList instance.

An `IsList` instance would have several advantages:

* We'd get the `[]` syntax with `-XOverloadedLists`, so one could write `[TF a, TF b, TF c] :: TypeRepMap f`
* We get an opportunity to implement `fromListN` more efficiently by preallocating vectors of the specified size.

**Comment by ChShersh** [comment]
@int-index Why the name is `hostWithM`? Maybe it should be `hoistWithA` and also create function with `Monad` constraint instead of `Applicative`?

**Comment by int-index** [comment]
The name doesn't matter, it can be `hoistWithA` if you want. I see no reason to add a `Monad`-specific version.

**Comment by int-index** [comment]
Sorry, I actually meant `hoistM` and `hoistA`, the `With` suffix is unnecessary.
