### ISSUE TITLE
Stack Haddock

### ISSUE THREAD

**Issue by vladciobanu** [kowainik/typerep-map#68]
On a fresh master checkout, running `stack haddock` yields:
```
haddock: internal error: ./z-typerep-map-z-typerep-extra-impls-0.3.0/z-typerep-map-z-typerep-extra-impls.haddock: openBinaryFile: does not exist (No such file or directory)
```

It seems like there might be something wrong with the `cabal` file, having two libraries in the same repository? Not entirely sure, I'm not very familiar with cabal. However, unfortunately, this is a dependency of `co-log`, and as we're trying to use it, we can no longer generate haddock docs of our lib & dependencies since it crashes (with the above error as well) on this dependency.

Do you have any idea what might be wrong?

**Comment by vrom911** [comment]
I'm very sorry that you are so sad about using this library. However, the problem you're facing is not in the `typerep-map` library. You can see that we have the documentation:

http://hackage.haskell.org/package/typerep-map-0.3.1/docs/

The problem is in Stack itself and you can see the issue in Stack repository:

https://github.com/commercialhaskell/stack/issues/3989

Haddock works with Cabal though. So you can continue the discussion in the Stack issue as there is nothing we can help you with here.
